# Generated by Django 2.0.2 on 2019-02-02 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('avatar', models.TextField(null=True)),
                ('totalCommits', models.IntegerField(default=0)),
                ('repos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=10)),
                ('reposcommits', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=10)),
                ('add', models.IntegerField(default=0)),
                ('delete', models.IntegerField(default=0)),
                ('gsoc', models.BooleanField(default=False)),
            ],
        ),
    ]
