# Generated by Django 2.0.2 on 2019-02-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190202_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gsoc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='repos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reposcommits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalCommits',
        ),
    ]
