# Generated by Django 2.0.2 on 2019-02-02 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190202_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gsoc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='repos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=10),
        ),
        migrations.AddField(
            model_name='user',
            name='reposcommits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=10),
        ),
        migrations.AddField(
            model_name='user',
            name='totalCommits',
            field=models.IntegerField(default=0),
        ),
    ]
