# Generated by Django 2.0.2 on 2019-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190202_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(unique=True),
        ),
    ]
