# Generated by Django 2.0.2 on 2019-02-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190202_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(unique=True)),
            ],
        ),
    ]
