# Generated by Django 2.0.2 on 2019-02-05 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_glist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reposcommits',
            new_name='reposCommits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='add',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete',
        ),
        migrations.AddField(
            model_name='user',
            name='reposAdd',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=10),
        ),
        migrations.AddField(
            model_name='user',
            name='reposDelete',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=10),
        ),
        migrations.AddField(
            model_name='user',
            name='totalAdd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totalDelete',
            field=models.IntegerField(default=0),
        ),
    ]
