# Generated by Django 2.0.2 on 2019-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190205_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalIssues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totalPRs',
            field=models.IntegerField(default=0),
        ),
    ]
