# Generated by Django 2.0.2 on 2019-02-06 20:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190206_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='repos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='reposAdd',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='reposCommits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='reposDelete',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=10),
        ),
    ]
