# Generated by Django 2.0.2 on 2019-02-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190206_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reposAdd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reposCommits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reposDelete',
        ),
    ]
