# Generated by Django 2.0.2 on 2019-02-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190206_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glist',
        ),
    ]
