# Generated by Django 2.0.2 on 2019-02-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_glist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totalAdd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalDelete',
        ),
    ]
