# Generated by Django 2.0.2 on 2019-02-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('repo', models.TextField(unique=True)),
                ('include', models.BooleanField(default=False)),
            ],
        ),
    ]
