# Generated by Django 2.1.5 on 2019-03-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMergedPRs', models.IntegerField(default=0)),
                ('totalOpenPRs', models.IntegerField(default=0)),
                ('totalIssues', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalCommits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalPRs',
        ),
        migrations.AddField(
            model_name='repository',
            name='openIssues',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='repository',
            name='totalIssues',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='relation',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Repository'),
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.ManyToManyField(through='core.Relation', to='core.User'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('user', 'repo')},
        ),
    ]
