# Generated by Django 2.2a1 on 2019-03-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='include',
            new_name='gsoc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalCommits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalIssues',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalPRs',
        ),
        migrations.AddField(
            model_name='repository',
            name='openIssues',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='repository',
            name='totalIssues',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(db_index=True),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMergedPRs', models.IntegerField(default=0)),
                ('totalOpenPRs', models.IntegerField(default=0)),
                ('totalIssues', models.IntegerField(default=0)),
                ('lastMergedPR', models.DateTimeField(auto_now=True)),
                ('lastOpenPR', models.DateTimeField(auto_now=True)),
                ('lastIssue', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'unique_together': {('user', 'repo')},
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.ManyToManyField(through='core.Relation', to='core.User'),
        ),
    ]
