# Generated by Django 2.2a1 on 2019-03-14 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190313_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='lastMergedPR',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 30, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
