# Generated by Django 2.2a1 on 2019-03-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190314_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='lastClosedPR',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
