# Generated by Django 2.2a1 on 2019-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_relation_lastclosedpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
